### ISSUE TITLE
Travis CI issue with SourceKitten

### ISSUE THREAD

**Issue by arguiot** [realm/jazzy#1053]
Hello, I tried to setup jazzy with Travis (so documentation updates by itself). Unfortunately, it throws me a weird issue:
```
jazzy --clean --no-objc --author Arthur Guiot --author_url https://arguiot.com --github_url https://github.com/orionsearch/SearchKit-Swift --output docs --xcodebuild-arguments -project,SearchKit-Swift.xcodeproj,-scheme,SearchKit-Swift -m SearchKit_Swift
/home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/bin/sourcekitten: 4: /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/bin/sourcekitten: Syntax error: word unexpected (expecting ")")
/home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/lib/jazzy/executable.rb:36:in `execute_command': /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/bin/sourcekitten ["doc", "--module-name", "SearchKit_Swift", "--", "-project", "SearchKit-Swift.xcodeproj", "-scheme", "SearchKit-Swift"] (RuntimeError)
/home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/bin/sourcekitten: 4: /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/bin/sourcekitten: Syntax error: word unexpected (expecting ")")
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:63:in `build'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/jazzy-0.9.5/bin/jazzy:15:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/jazzy:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/jazzy:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
The command "jazzy --clean --no-objc --author Arthur Guiot --author_url https://arguiot.com --github_url https://github.com/orionsearch/SearchKit-Swift --output docs --xcodebuild-arguments -project,SearchKit-Swift.xcodeproj,-scheme,SearchKit-Swift -m SearchKit_Swift" exited with 1.
```
The command runs on my machine, but not on Travis.

**Comment by johnfairh** [comment]
The error is coming from the shell on travis trying to grok the sourcekitten executable.  Worth a sanity check that your travis is set to the same OS as your machine (and not its default of linux, for eg.)

**Comment by arguiot** [comment]
Sure, here is my `.travis.yml`:
```yml
language:       ruby
osx_image:      xcode10.1
install:
  # Install Jazzy and dependencies
  - gem install jazzy
script:
  - "jazzy --clean --no-objc --author Arthur Guiot --author_url https://arguiot.com --github_url https://github.com/orionsearch/SearchKit-Swift --output docs --xcodebuild-arguments -project,SearchKit-Swift.xcodeproj,-scheme,SearchKit-Swift -m SearchKit_Swift --theme fullwidth"

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir:    docs
  on:
    branch:     master
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
```
