### ISSUE TITLE
custom categories for classes

### ISSUE THREAD

**Issue by khaledbohout2** [realm/jazzy#1235]
is there any way to customize categorization in the left bar ? not just classes , i want to categorize it with something like (user classes - product classes . etc)

**Comment by johnfairh** [comment]
Yes - in .jazzy.yaml something like:
```yaml
custom_categories:
  - name: User Classes
    children:
    - User Class1
    - User Class2

  - name: Product Classes
    children:
    - PC1
    - PC2
```
[A real-world example](https://github.com/bustoutsolutions/siesta/blob/master/.jazzy.yaml).
