### ISSUE TITLE
`block in next_doc_module_group': undefined local variable or method `_1' for Jazzy::SourceKitten:Module (NameError)

### ISSUE THREAD

**Issue by nabhanh** [realm/jazzy#1388]
I am trying to generate docs for a XCode Project. The jazzy command builds the code using xcode build and then starts generating the docs for each file but at the end this is the error.
```bash
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:922:in `block in next_doc_module_group': undefined local variable or method `_1' for Jazzy::SourceKitten:Module (NameError)
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:922:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:922:in `partition'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:922:in `next_doc_module_group'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:908:in `merge_code_declaration'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:792:in `merge_type_and_extensions'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:779:in `merge_declarations'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:686:in `block in deduplicate_declarations'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:684:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:684:in `flat_map'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:684:in `deduplicate_declarations'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:1089:in `parse'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:157:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:88:in `build'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.15.0/bin/jazzy:16:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

**Comment by nabhanh** [comment]
Additional Info:
Ruby Version: 2.6.10
Jazzy Version: 0.15.0
Config File:
```yaml
# Ordered by output of `jazzy — help config`
output: docs
clean: true
xcodebuild_arguments:
  - -workspace
  - workspace_file_name
  - -scheme
  - schemename
  - CODE_SIGNING_ALLOWED = NO
  - CODE_SIGNING_REQUIRED = NO
  - CODE_SIGNING_IDENTITY = ""
readme: README.md
min_acl: public
theme: apple
```
I have not specified the module name here since it's the same as the scheme name
