### ISSUE TITLE
yams conversion question

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#470]
So this is my current jazzy setup

```bash
jazzy --output docs/DataRecorder --clean   --xcodebuild-arguments -scheme,DataRecorder
```

I tried to convert this into yaml

```yaml


module_name: DataRecorder
clean: true
output: docs/DataRecorder
xcodebuild_settings:
  - "-scheme,DataRecorder"

```

I'm assuming its an issue with my `xcodebuild_settings` because its not working correctly - but i'm not sure what i'm doing wrong.
