### ISSUE TITLE
xcodebuild_arguments in yaml

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#471]
What is the correct way to convert from:

```bash
jazzy --output docs/DataRecorder --clean  --xcodebuild-arguments -scheme,DataRecorder
```

to a YAML implementation?

```yaml

module_name: DataRecorder
clean: true
output: docs/DataRecorder
xcodebuild_arguments:
 - '-scheme,DataRecorder'
```
doesn't seem to be cutting it.

I've tried a variety of combos - but it just doesn't seem to be picking up the correct scheme.  I'm sure i'm missing something obvious.

> /Users/jstein/.rvm/gems/ruby-2.1.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': > /Users/jstein/.rvm/gems/ruby-2.1.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--module-name", "DataRecorder", "-scheme,DataRecorder"]

**Comment by jeeftor** [comment]
Looks like this might have done it.  

```yaml
module_name: DataRecorder
clean: true
output: docs/DataRecorder
xcodebuild_arguments:
 - -scheme
 - DataRecorder
```
