### ISSUE TITLE
Objective-C : Unable to find <MOD/MOD.h>

### ISSUE THREAD

**Issue by lagapollo** [realm/jazzy#486]
Hi there, 

 I'm pretty new with jazzy. I want to document my objective-c pod project.

I'm using this jazzy.yaml file : 

``` yaml
objc_mode: true

clean: true

author: MyCompany #auteur du projet

author_url: https://github.com/MyCompany

github_url: https://github.com/MyCompany/MyMod #URL du github

github_file_prefix: ./ #chemin où se trouve le fichier .git du projet

module_version: 1.0 #version du projet

umbrella-header: MyMod/MyMod.h

framework-root: ./

module: MyModName #nom du module - il doit correspondre au nom du projet sur xCode, très important !

#min_acl: private #cette donnée permet d'indiquer que les fonctions/paramètres privés doivent être inclus dans la doc

source_directory: ./ #chemin où se trouve le fichier .xcodeproj du projet


module_name: MyModName

author_name: MyCompany

xcodebuild_arguments: [--objc, MyModName/MyModName.h, -x, objective-c, -isysroot, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk, -I, `/Users/me/Documents/workspace/directory/MyModName/]

```

with "jazzy" as command-line. 

I have the following ouptut : 

`MyModName/MyModName.h:20:9: fatal error: 'MyModName/PublicHeader.h' file not found`

To be sure of what i'm doing, I tried to generate locally Realm documentation, jsut as said in readme.md in jazzy repo.

I cloned realm and enter command : 

``` bash
jazzy \
>   --objc \
>   --clean \
>   --author Realm \
>   --author_url https://realm.io \
>   --github_url https://github.com/realm/realm-cocoa \
>   --github-file-prefix https://github.com/realm/realm-cocoa/tree/v0.96.2 \
>   --module-version 0.96.2 \
>   --umbrella-header Realm/Realm.h \
>   --framework-root . \
>   --module Realm \
>   --root-url https://realm.io/docs/objc/0.96.2/api/ \
>   --output docs/objc_output \
>   --theme docs/themes
```

and got the following error message: 

``` bash
/Users/me/Documents/workspace/tmp/Realm/realm-cocoa/Realm/Realm.h:25:9: fatal error: 'Realm/RLMPlatform.h' file not found
building site
```

I got the same error in both case...

Can someone help me please ?
