### ISSUE TITLE
xcodebuild arguments issue

### ISSUE THREAD

**Issue by poborin** [realm/jazzy#643]
I'm using a .jazzy.yaml file to configure a project
```yaml
author: Intelematics Pty Ltd
author_url: http://www.intelematics.com
module: DanlawDriver

clean: true
objc: true
sdk: iphonesimulator
framework_root: ./
source_directory: ./
umbrella_header: DanlawDriver/DanlawDriver.h
xcodebuild_arguments: [-scheme, DanlawDriver, -project, ./DanlawDriver.xcodeproj]
```

if I set **-scheme** and **-project** in `xcodebuild_arguments` I get an error
```
Unrecognized arguments: -semch, -jrpcoet
/Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-scheme", "DanlawDriver", "-project", "./DanlawDriver.xcodeproj"] (RuntimeError)

Unrecognized arguments: -semch, -jrpcoet
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:147:in `run_sourcekitten'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:64:in `block in build'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:62:in `chdir'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:62:in `build'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/bin/jazzy:15:in `<top (required)>'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/bin/jazzy:23:in `load'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/bin/jazzy:23:in `<main>'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
       	from /Users/poborin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
If I don't set them I get
```
fatal error: 'BTInterfaces/BTInterfaces.h' file not found
```
