### ISSUE TITLE
Does custom_categories support reg expression?

### ISSUE THREAD

**Issue by liuxuan30** [realm/jazzy#688]
one question, it seems like custom_categories does not support reg expression?
Let's say I have many classes with some prefix: some starts with Line, some starts with Bars:

BarChartView.swift,
BarChartData.swift,
LineChartView.swift,
LineChartDataSet.swift

I want to group them into Line Type and Bar Type,
```
custom_categories:
  name: Bar Type
     children:
     - Bar*
  name: Line Type
     children:
     - Line*
```
It won't have any effect. Instead, I have manually list all the classes. Am I wrong?
