### ISSUE TITLE
Lists need to get their bullets back!

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#783]
Item lists in documentation comments get `list-style-type: none;` from `.item`, which is used for structuring the pages. Also, the indentation is off.

Adding

```css
div.abstract li { 
	list-style-type: disc; 
	left-margin: 2em; 
}
```

works around the issues at least in some cases, but I think some changes to the HTML are in order for a clean(er) result.
