### ISSUE TITLE
Error when add pod for target

### ISSUE THREAD

**Issue by junestchick** [realm/jazzy#989]
Everything was ok until I used RealmSwift for target. Here is my pod file: 

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'zzz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zzz
  pod 'Alamofire', '4.7.2'
  pod 'SwiftLint'
  pod 'Localize-Swift'
  pod 'IQKeyboardManager', '6.0.2'
  pod 'SVProgressHUD'
  pod 'Realm'
  pod 'Hero'
  pod 'AEXML', '4.3.0'
  pod 'RealmSwift'
  pod 'Toast-Swift'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'zzz1' do
    use_frameworks!
    pod 'RealmSwift'
end
```

Here is log.
https://pastebin.com/wVjzyR2k

And config: 

```yaml
module: cpa
author: C. J.
exclude:
  - "**/*-Ext.swift"
  - "zzz/zzz/Sources/Common/Library/*.swift"
skip_undocumented: true
clean: true
use_safe_filenames: true
hide_documentation_coverage: true
min_acl: private
```

Thanks!!
